"""
Django settings for crvslearning project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%bwq)y#z_--6j5qab#2(wo(tzy!=bslgofl&kt9nu$j9=x))_h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Configuration CORS
CORS_ALLOW_ALL_ORIGINS = True  # En développement uniquement
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'corsheaders',                   # Pour gérer les en-têtes CORS
    'django.contrib.admin',          # administration
    'django.contrib.auth',           # gestion des utilisateurs
    'django.contrib.contenttypes',   # gestion des types de contenus
    'django.contrib.sessions',       # sessions utilisateurs
    'django.contrib.messages',       # système de messages
    'django.contrib.staticfiles',    # fichiers statiques (css, js...)
    'django.contrib.sites',          # gestion des sites (important pour admin)
    'django.contrib.humanize',       # filtres pour templates
    'nested_admin',                  # pour l'admin imbriqué
    # Tes apps custom
    'users',
    'courses',
    'evaluations',
    'notifications',
    'certifications',
    'classrooms',
    'channels',
    'subscriptions',
    'documentation',
    'exercices',
    'crispy_forms',
    'crispy_bootstrap5',
    'forum.apps.ForumConfig',     # Application Forum Q/R avec config personnalisée
    'tracking',  # Suivi des apprenants et progression des cours
    'payments',  # Gestion des paiements
    'chat',  # Application de chat en temps réel
]

# Configuration de crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Configuration des sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Utiliser la base de données pour les sessions
SESSION_COOKIE_NAME = 'crvslearning_sessionid'  # Nom du cookie de session
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_COOKIE_SECURE = not DEBUG  # True en production (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True  # Rafraîchir le cookie de session à chaque requête
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # La session expire après SESSION_COOKIE_AGE

# Configuration CSRF
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# Configuration d'authentification
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend d'authentification par défaut
]

AUTH_USER_MODEL = 'users.CustomUser'  # Utiliser le modèle CustomUser

SITE_ID = 1  # IMPORTANT pour django.contrib.sites

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Doit être placé avant CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tracking.middleware.ActivityTrackingMiddleware',  # Suivi des activités
    'tracking.middleware.CourseReminderMiddleware',  # Rappels de cours inachevés
    'users.middleware.LastSeenMiddleware',  # Met à jour last_seen automatiquement
    'users.middleware.AdminRedirectMiddleware',  # Redirection des admins
    'users.middleware.UserPreferencesMiddleware',  # Gestion des préférences utilisateur
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crvslearning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- ajoute ici
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications',
            ],
        },
    },
]


WSGI_APPLICATION = 'crvslearning.wsgi.application'
ASGI_APPLICATION = 'crvslearning.asgi.application'

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = 'users.CustomUser'

# Paramètres d'authentification
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'users:profile'
LOGOUT_REDIRECT_URL = 'users:dashboard'

# Configuration des sessions
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_COOKIE_SECURE = not DEBUG  # True en production (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True  # Rafraîchir le cookie de session à chaque requête
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # La session expire après SESSION_COOKIE_AGE

# Configuration CSRF
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# Configuration Email pour le développement
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@crvslearning.com'
SERVER_EMAIL = 'noreply@crvslearning.com'

# Pour la production, commentez les lignes ci-dessus et décommentez ci-dessous :
"""
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre-app-password'
# DEFAULT_FROM_EMAIL = 'noreply@crvslearning.com'
# SERVER_EMAIL = 'noreply@crvslearning.com'
"""

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuration de Jazzmin (désactivé)
# JAZZMIN_SETTINGS = {
#     # Thème sombre
#     "theme": "darkly",
#     "dark_mode_theme": True,  # Force le mode sombre
#     
#     # Personnalisation de l'interface
#     "site_title": "CRVS Learning Admin",
#     "site_header": "CRVS Learning",
#     "site_brand": "CRVS Learning",
#     "site_logo": "img/logo.png",
#     "welcome_sign": "Bienvenue dans l'administration CRVS Learning",
#     
#     # Personnalisation des couleurs
#     "theme_colors": {
#         "primary": "#3498db",
#         "secondary": "#2ecc71",
#         "info": "#17a2b8",
#         "warning": "#f39c12",
#         "danger": "#e74c3c",
#         "success": "#00bc8c"
#     },
#     
#     # Désactiver la sélection de thème par l'utilisateur
#     "show_ui_builder": False,
#     
#     # Personnalisation du menu
#     "topmenu_links": [
#         {"name": "Accueil",  "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"app": "courses", "permissions": ["courses.view_course"]},
#     ],
#     
#     # Barre latérale personnalisée
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "hide_apps": [],
#     "hide_models": [],
#     
#     # Options d'interface utilisateur
#     "changeform_format": "horizontal_tabs",
#     "related_modal_active": True,
#     "custom_css": "admin/windows11_ps5_totaldark.css",  # Thème TOTAL-DARK - écrase TOUS les champs
#     "custom_js": None,
# }

# Internationalization
LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# For collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Allow embedding pages (PDF) within same-origin iframes/objects for preview modals
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/users/login/'

import os
# Channels layer: use Redis if REDIS_URL is provided, otherwise in-memory (dev)
_redis_url = os.environ.get('REDIS_URL')

# Configuration des canaux (Channels)
# En développement, utiliser InMemoryChannelLayer si Redis n'est pas disponible
try:
    import redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [("localhost", 6380)],  # Port 6380 car Redis tourne sur ce port
                "symmetric_encryption_keys": [SECRET_KEY],
            },
        },
    }
except ImportError:
    # Redis non disponible - utiliser la mémoire pour le développement
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# Configuration des messages
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# CSRF_TRUSTED_ORIGINS = [
#     "https://crvslearning.etatcivil.cm",
#     "https://meet.etatcivil.cm",
# ]

# MEETING_BASE_URL = "https://meet.etatcivil.cm"

# Configuration des logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'courses': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
