# Generated by Django 5.2.7 on 2026-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='universite',
            field=models.CharField(blank=True, choices=[('uya1', 'Université de Yaoundé 1'), ('uya2', 'Université de Yaoundé 2 - Soa'), ('ucac', "Université Catholique d'Afrique Centrale - UCAC"), ('injs', 'INJS'), ('ud', 'Université de Douala'), ('ub', 'Université de Bertoua'), ('uds', 'Université de Dschang'), ('mantanfen', 'MANTANFEN'), ('istag', 'ISTAG'), ('saintou', 'Institut Siantou')], max_length=20, null=True, verbose_name='Établissement universitaire'),
        ),
    ]
