# Generated by Django 5.2.7 on 2026-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_universite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indique si le compte formateur a été approuvé par un administrateur', verbose_name='Compte validé'),
        ),
    ]
