# Generated by Django 5.2.7 on 2026-01-26 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_modules', models.JSONField(blank=True, default=list, help_text='Liste des IDs des modules favoris', verbose_name='Modules favoris')),
                ('favorite_categories', models.JSONField(blank=True, default=list, help_text='Liste des IDs des catégories favorites', verbose_name='Catégories favorites')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Auto')], default='light', max_length=20, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('auto_play_video', models.BooleanField(default=False)),
                ('show_progress', models.BooleanField(default=True)),
                ('download_for_offline', models.BooleanField(default=False)),
                ('session_preferences', models.JSONField(blank=True, default=dict, help_text='Préférences temporaires stockées en session', verbose_name='Préférences de session')),
                ('cookie_consent', models.BooleanField(default=False, verbose_name='Consentement cookies')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
            },
        ),
    ]
