# Generated by Django 5.2.8 on 2026-02-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_approved_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Entrez votre date de naissance', null=True, verbose_name='Date de naissance'),
        ),
    ]
