# Generated by Django 5.2.8 on 2026-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fosa_profession',
            field=models.CharField(blank=True, choices=[('medecin', 'Médecin'), ('sage_femme', 'Sage femme'), ('infirmiere', 'Infirmière'), ('aide_soignant', 'Aide soignant')], max_length=20, null=True, verbose_name='Profession (FOSA)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sante_service',
            field=models.CharField(blank=True, help_text="Entrez votre service au sein de l'administration centrale", max_length=100, null=True, verbose_name='Service (Administration centrale)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sante_type',
            field=models.CharField(blank=True, choices=[('admin_centrale', 'Administration centrale'), ('fosa', 'FOSA (Formation Sanitaire)')], max_length=20, null=True, verbose_name='Type de structure sanitaire'),
        ),
    ]
