# Generated by Django 5.2.8 on 2026-04-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_fosa_profession_customuser_sante_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lieu_affectation_bunec',
            field=models.CharField(blank=True, choices=[('direction_generale', 'Direction Générale'), ('agence_regionale', 'Agence Régionale')], help_text="Sélectionnez votre lieu d'affectation à la BUNEC", max_length=20, null=True, verbose_name="Lieu d'affectation BUNEC"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_bunec',
            field=models.CharField(blank=True, help_text='Sélectionnez votre service spécifique à la BUNEC', max_length=50, null=True, verbose_name='Service BUNEC'),
        ),
    ]
