# Generated by Django 5.2.8 on 2026-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_lieu_affectation_bunec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lieu_affectation_bunec',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service_bunec',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bunec_service',
            field=models.CharField(blank=True, help_text='Sélectionnez votre service spécifique', max_length=50, null=True, verbose_name='Service BUNEC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bunec_structure',
            field=models.CharField(blank=True, choices=[('direction_generale', 'Direction Générale'), ('agence_regionale', 'Agence Régionale')], help_text='Sélectionnez votre structure au sein de la BUNEC', max_length=30, null=True, verbose_name='Structure BUNEC'),
        ),
    ]
