# Generated by Django 5.2.7 on 2026-01-26 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroommembership',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='classroommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classrooms.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroommembership',
            unique_together={('classroom', 'user')},
        ),
    ]
