# Generated by Django 5.2.8 on 2026-02-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_add_template_field'),
        ('certifications', '0003_initial'),
    ]

    operations = [
    ]
