# Generated by Django 5.2.8 on 2026-02-14 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_merge_0002_add_template_field_0003_initial'),
        ('courses', '0012_learningpathtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(blank=True, help_text='Titre de la certification', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['user', 'issued_at'], name='certificati_user_id_9fff49_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['template', 'is_valid'], name='certificati_templat_44051b_idx'),
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('user', 'course', 'level'), name='unique_user_course_level'),
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('user', 'template', 'level'), name='unique_user_template_level'),
        ),
    ]
