# Generated by Django 4.2.7 on 2026-05-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Dernière activité dans le cours', null=True)),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Pourcentage de progression actuel')),
                ('is_active', models.BooleanField(default=True, help_text='Rappel actif ou non')),
                ('reminder_count', models.PositiveIntegerField(default=0, help_text='Nombre de rappels envoyés')),
                ('last_reminder_sent', models.DateTimeField(blank=True, help_text='Date du dernier rappel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='courses.course')),
                ('current_lesson', models.ForeignKey(blank=True, help_text='Dernière leçon consultée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reminders', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Rappel de cours',
                'verbose_name_plural': 'Rappels de cours',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
