# Generated by Django 5.2.7 on 2026-01-26 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_module_is_paid_module_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('duration_days', models.PositiveIntegerField(help_text="Durée de l'abonnement en jours. 0 pour illimité", verbose_name='Durée (jours)')),
                ('max_modules', models.PositiveIntegerField(blank=True, help_text='Nombre de modules inclus. Laisser vide pour illimité', null=True, verbose_name='Nombre de modules maximum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant payé en FCFA', max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, help_text='Ex: Orange Money, MTN Mobile Money, Carte bancaire', max_length=50, null=True, verbose_name='Méthode de paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='payments.payment', verbose_name='Paiement initial')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.paymentplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'accès")),
                ('expires_at', models.DateTimeField(blank=True, help_text='Laisser vide pour un accès permanent', null=True, verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Accès actif')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='courses.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Accès au module',
                'verbose_name_plural': 'Accès aux modules',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
