# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_subject_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(max_length=100, default='CRVS Learning'),
        ),
    ]
