# Generated by Django 5.2.8 on 2026-02-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_sender'),
        ('notifications', '0004_complete_model'),
    ]

    operations = [
    ]
