# Generated by Django 5.2.8 on 2026-02-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merge_0003_notification_sender_0004_complete_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/attachments/%Y/%m/%d/', verbose_name='Pièce jointe'),
        ),
    ]
