# Generated by Django 5.2.8 on 2026-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Vote positif'), ('down', 'Vote négatif')], default='up', max_length=4),
        ),
    ]
