# Generated by Django 5.2.7 on 2026-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Si coché, le module nécessite un paiement pour y accéder', verbose_name='Payant'),
        ),
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix du module en FCFA', max_digits=10, verbose_name='Prix'),
        ),
    ]
