# Generated by Django 5.2.7 on 2026-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_is_paid_module_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_promotionnelle',
            field=models.FileField(blank=True, help_text='Vidéo promotionnelle gratuite accessible à tous (format MP4 recommandé)', null=True, upload_to='course/promotional_videos/'),
        ),
    ]
