# Generated by Django 5.2.7 on 2026-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_video_promotionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la catégorie', null=True, upload_to='categories/images/'),
        ),
    ]
