# Generated by Django 5.2.7 on 2026-02-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cible',
            field=models.CharField(choices=[('bunec', 'BUNEC'), ('commune', 'Commune'), ('minsante', 'Ministère de la Santé'), ('minddevel', 'Ministère du Développement'), ('ong', 'ONG'), ('universite', 'Université'), ('consultant', 'Consultant'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], default='autre', help_text='Sélectionnez la structure cible pour ce cours', max_length=20, verbose_name='Structure cible'),
        ),
        migrations.AddField(
            model_name='course',
            name='niveau',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', help_text='Sélectionnez le niveau du cours', max_length=20, verbose_name='Niveau'),
        ),
    ]
