# Generated by Django 5.2.7 on 2026-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_cible_course_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la compétence', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la compétence')),
                ('icone', models.CharField(blank=True, help_text="Classe d'icône (ex: bi-code-slash)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='competences',
            field=models.ManyToManyField(blank=True, help_text="Sélectionnez les compétences que l'apprenant acquerra en suivant ce cours", to='courses.competence', verbose_name='Compétences acquises'),
        ),
    ]
