# Generated by Django 5.2.7 on 2026-02-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_competence_course_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='icone',
        ),
    ]
