# Generated by Django 5.2.7 on 2026-02-03 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_competence_icone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_score', models.FloatField(default=0.0, help_text='Score basé sur la progression des leçons (0-100)', verbose_name='score leçons')),
                ('quiz_score', models.FloatField(default=0.0, help_text='Score moyen des quiz (0-100)', verbose_name='score quiz')),
                ('final_score', models.FloatField(default=0.0, help_text='Score final pondéré (0-100)', verbose_name='score final')),
                ('lesson_weight', models.FloatField(default=0.3, help_text='Poids des leçons dans le score final', verbose_name='poids leçons')),
                ('quiz_weight', models.FloatField(default=0.7, help_text='Poids des quiz dans le score final', verbose_name='poids quiz')),
                ('is_passed', models.BooleanField(default=False, help_text='Le cours est réussi si score >= seuil', verbose_name='réussi')),
                ('passing_score', models.FloatField(default=70.0, help_text='Score minimum pour réussir le cours', verbose_name='seuil de réussite')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de complétion')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Résultat de cours',
                'verbose_name_plural': 'Résultats de cours',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre du quiz')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('total_questions', models.PositiveIntegerField(default=5, verbose_name='nombre total de questions')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Score minimum pour réussir (en %)', verbose_name='score de réussite')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Temps limite en minutes, vide pour illimité', null=True, verbose_name='limite de temps (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score en pourcentage', verbose_name='score obtenu')),
                ('is_passed', models.BooleanField(default=False, verbose_name='réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de fin')),
                ('time_taken', models.DurationField(blank=True, help_text='Temps pris pour compléter le quiz', null=True, verbose_name='temps passé')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
            },
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='auto_completed',
            field=models.BooleanField(default=False, help_text='Complété automatiquement à 80%', verbose_name='complétion automatique'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='auto_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date complétion auto'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='is_fully_completed',
            field=models.BooleanField(default=False, help_text='Leçon 100% complétée (auto + manuel)', verbose_name='pleinement complétée'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='manually_marked',
            field=models.BooleanField(default=False, help_text="Marqué comme terminé par l'utilisateur", verbose_name='marqué manuellement'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='manually_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date marquage manuel'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_percentage',
            field=models.FloatField(default=0.0, help_text='Pourcentage de la vidéo regardée', verbose_name='pourcentage visionné'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.DurationField(blank=True, help_text='Temps total passé sur la leçon', null=True, verbose_name='temps de visionnage'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson', 'is_fully_completed'], name='courses_les_user_id_12f29b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['auto_completed', 'manually_marked'], name='courses_les_auto_co_9d5f2a_idx'),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='cours'),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='leçon'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['user', 'course', 'is_passed'], name='courses_cou_user_id_757c28_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['course', 'final_score'], name='courses_cou_course__b40414_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['-final_score', 'completed_at'], name='courses_cou_final_s_04b46c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson', 'is_active'], name='courses_qui_lesson__4870e0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user', 'is_passed'], name='courses_qui_quiz_id_a4a427_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'score'], name='courses_qui_user_id_32f8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['-score', 'completed_at'], name='courses_qui_score_3e1ca1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user', 'started_at')},
        ),
    ]
