# Generated by Django 5.2.7 on 2026-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseresult_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la structure cible')),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône (ex: bi-building)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Structure cible',
                'verbose_name_plural': 'Structures cibles',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='cible',
        ),
        migrations.AddField(
            model_name='course',
            name='cibles',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez une ou plusieurs structures cibles pour ce cours', to='courses.cible', verbose_name='Structures cibles'),
        ),
    ]
