# Generated by Django 5.2.7 on 2026-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_cible_remove_course_cible_course_cibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cibles',
        ),
        migrations.AddField(
            model_name='course',
            name='cible',
            field=models.CharField(choices=[('bunec', 'BUNEC'), ('commune', 'Commune'), ('minsante', 'Ministère de la Santé'), ('minddevel', 'Ministère du Développement'), ('ong', 'ONG'), ('universite', 'Université'), ('consultant', 'Consultant'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], default='autre', help_text='Sélectionnez la structure cible pour ce cours', max_length=20, verbose_name='Structure cible'),
        ),
        migrations.DeleteModel(
            name='Cible',
        ),
    ]
