# Generated by Django 5.2.7 on 2026-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_cibles_course_cible_delete_cible'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du parcours')),
                ('structure', models.CharField(choices=[('commune', 'Commune'), ('minsante', 'Ministère de la Santé'), ('bunec', 'BUNEC'), ('universite', 'Université'), ('ong', 'ONG'), ('consultant', 'Consultant'), ('partenaire', 'Partenaire'), ('autre', 'Autre'), ('multi_structure', 'Multi-structures')], max_length=20, verbose_name='Structure cible')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20, verbose_name='Niveau')),
                ('description', models.TextField(help_text="Description détaillée du parcours d'apprentissage", verbose_name='Description')),
                ('sequence', models.JSONField(default=dict, help_text='Structure et ordre des modules', verbose_name='Séquence recommandée')),
                ('estimated_duration', models.DurationField(help_text='Durée estimée du parcours', verbose_name='Durée estimée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('categories', models.ManyToManyField(blank=True, related_name='path_templates', to='courses.category', verbose_name='Catégories')),
                ('courses', models.ManyToManyField(blank=True, related_name='path_templates', to='courses.course', verbose_name='Cours inclus')),
            ],
            options={
                'verbose_name': 'Template de parcours',
                'verbose_name_plural': 'Templates de parcours',
                'ordering': ['structure', 'level', 'name'],
                'indexes': [models.Index(fields=['structure', 'level'], name='courses_lea_structu_7109e5_idx'), models.Index(fields=['is_active'], name='courses_lea_is_acti_10aaa0_idx'), models.Index(fields=['created_at'], name='courses_lea_created_6839c1_idx')],
                'unique_together': {('structure', 'level', 'name')},
            },
        ),
    ]
