# Generated by Django 5.2.8 on 2026-02-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_learningpathtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la catégorie'),
        ),
    ]
