# Generated by Django 5.2.7 on 2026-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordre du cours dans le parcours (0 = non défini, 1+ = ordre séquentiel)', verbose_name='Ordre'),
        ),
    ]
