# Generated by Django 5.2.8 on 2026-02-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='certification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de certification'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='certification_obtained',
            field=models.BooleanField(default=False, verbose_name='Certification obtenue'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='certification_progress',
            field=models.FloatField(default=0.0, verbose_name='Progression vers la certification (%)'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='last_certification_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification de certification'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_paths', to='courses.learningpathtemplate', verbose_name='Template du parcours'),
        ),
    ]
