# Generated by Django 5.2.8 on 2026-02-13 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_learningpath_certification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathtemplate',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs spécifiques assignés à ce template (en plus de la structure)', related_name='assigned_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs assignés'),
        ),
        migrations.AddField(
            model_name='learningpathtemplate',
            name='assignment_mode',
            field=models.CharField(choices=[('structure_only', 'Structure uniquement'), ('users_only', 'Utilisateurs spécifiques uniquement'), ('both', 'Structure ET utilisateurs spécifiques')], default='structure_only', help_text='Comment ce template doit être assigné aux utilisateurs', max_length=20, verbose_name="Mode d'assignation"),
        ),
        migrations.AddField(
            model_name='learningpathtemplate',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Envoyer des notifications aux utilisateurs concernés', verbose_name='Activer les notifications'),
        ),
        migrations.AddField(
            model_name='learningpathtemplate',
            name='notification_message',
            field=models.TextField(blank=True, help_text='Message personnalisé pour les notifications (laisser vide pour utiliser le message par défaut)', verbose_name='Message de notification'),
        ),
    ]
