# Generated by Django 5.2.8 on 2026-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_learningpathtemplate_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathtemplate',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Sujet personnalisé pour les emails (laisser vide pour utiliser le sujet par défaut)', max_length=200, verbose_name="Sujet de l'email"),
        ),
        migrations.AddField(
            model_name='learningpathtemplate',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, help_text='Envoyer également les notifications par email aux utilisateurs', verbose_name='Activer les notifications par email'),
        ),
    ]
