# Generated by Django 5.2.8 on 2026-02-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_learningpathtemplate_email_subject_and_more'),
        ('courses', 'add_certification_fields'),
    ]

    operations = [
    ]
