# Generated by Django 5.2.8 on 2026-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_merge_20260213_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathtemplate',
            name='additional_structures',
            field=models.CharField(blank=True, help_text='Sélectionnez les structures additionnelles (séparées par des virgules)', max_length=200, verbose_name='Structures additionnelles'),
        ),
    ]
